services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Pastry
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init_pastry_db.sql:/docker-entrypoint-initdb.d/init_pastry_db.sql

  backend:
    build:
      context: ./PastryFloraBack
      dockerfile: Dockerfile
    container_name: pastry_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=Pastry
    volumes:
      - ./PastryFloraBack:/app
      - /app/node_modules
    depends_on:
      - db
    command: ["sh", "-c", "sleep 15 && npx ts-node insertBranches.ts && npx ts-node insertTestUser.ts && npm run dev"]

  frontend:
    build:
      context: ./PastryFloraFront
      dockerfile: Dockerfile
    container_name: pastry_frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000/api
    volumes:
      - ./PastryFloraFront:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mysql_data:
